### ISSUE TITLE
Notification in media control carousel

### ISSUE THREAD

**Issue by silfversound** [ghenry22/cordova-music-controls-plugin#79]
With Android 11 and 12 you are able to have the notification in a media control carousel like this:
https://android-developers.googleblog.com/2020/08/playing-nicely-with-media-controls.html

I'm getting my notification in the notifications list and not in the media control carousel. Have I missed anything or is it not implemented yet in this plugin?

**Comment by bikubi** [comment]
The article you mention says:

> Now, the really good news. As long as you're using [MediaStyle](https://developer.android.com/reference/androidx/media/app/NotificationCompat.MediaStyle) with a valid [MediaSession](https://developer.android.com/guide/topics/media-apps/working-with-a-media-session) token (both available since Lollipop API 21), media controls will be displayed for your app automatically - no extra work for you!

And I can find `MediaStyle` mentioned in the code, it goes back to #65, but it looks more like a shim and less like the "recap" in the article.

I suspect that the "shim" does not suffice (any more)?

EDIT: btw, I'm on Android 13 and also getting a "regular" notification and not the carousely one I know from Android 10.

**Comment by bikubi** [comment]
Looks like `MediaStyle` is missing the `MediaSession` token. I've fixed in my fork, seems to work; tested on Android 10 and 13 devices.
https://github.com/bikubi/cordova-plugin-music-controls2/commit/47a87f309db11d2469eb6b1b973c64eea6745d19

**Comment by ghenry22** [comment]
This is fixed in v3.0.7
